## Numpy array and basics
learn about numpy 

In [1]:
import numpy as np 

### Creating array from list

In [8]:
arr_1d=np.array([1,2,3,4])
print("1D Array",arr_1d)

arr_2d = np.array([[1,2,3],[5,6,7]])    # 2d array mai single parameter hi pass hona chahiye isliye ek hi bracket mai 2 beracket pass kiye hai 
print("2D Array",arr_2d)

1D Array [1 2 3 4]
2D Array [[1 2 3]
 [5 6 7]]


### List vs numpy array

In [ ]:
py_list = [1,2,3]
print("Python List Multuplication",py_list*2)

np_array= np.array([1,2,3])  # element wise multiplication
print("Python Array Multiplication" , np_array * 2)


Python List Multuplication [1, 2, 3, 1, 2, 3]
Python Array Multiplication [2 4 6]


In [ ]:
import time               # ye bas efficiency pata krne ke liye likha hai ki numpy kyu jyada efficient hai
start = time.time()
py_list= [i*2 for i in range(1000000)]
print("\n List operation time:" , time.time() - start)   # time.time() - start likhe se   time mil jaega to execute that particular task

start = time.time()
np_array = np.arange(1000000)*2
print("\n Numpy operation time : " , time.time() - start) 


 List operation time: 0.11638951301574707

 Numpy operation time :  0.005579948425292969


### Creating Array from Scratch

In [ ]:
zeros = np.zeros ((3,4))
print("Zeros array: \n", zeros)

ones = np.ones ((2,5))
print("Ones array:\n" , ones)


full= np.full( (2,2),7)         # ismai apan ne bola 2 rows aur 2 columns ki array milegi jismai 7 hi likha hoga bas
print("Full array:\n" , full)


random = np.random.random( (2,3))   # 0 se 1 ke beech mai aati hai 
print("Random array:\n" , random)

sequence = np.arange(0 ,10 ,3)   # non-inclusive hota hai   aur 0 se start 3 ka gap 10 tak 
print("Sequence array:\n" , sequence)

Zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Full array:
 [[7 7]
 [7 7]]
Random array:
 [[0.65985737 0.17765705 0.66068956]
 [0.54469093 0.36789271 0.86980608]]
Sequence array:
 [0 3 6 9]


### Vector , Matrix and Tensor

In [24]:
vector = np.array ( [1,2,3])
print( " Vector:" , vector)

matrix = np.array ( [ [1,2,3], [4,5,6]])
print("Matrix:" , matrix)

tensor = np.array ([[[1,2],[3,4]],[[5,6],[7,8]]])     # Tensor mai dimensions multiple hoti hai
print("Tensor:" , tensor)

 Vector: [1 2 3]
Matrix: [[1 2 3]
 [4 5 6]]
Tensor: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties

In [29]:
arr= np.array ( [[1,2,3], [4,5,6.8]])         # keval ek element change krte hi Dtype change ho jaega 
print ("Shape", arr.shape)
print ("Dimension", arr.ndim)    # kyuki array 
print ("Size", arr.size)
print ("Dtype", arr.dtype)   # Datatype


Shape (2, 3)
Dimension 2
Size 6
Dtype float64


### Array Reshaping


In [37]:
arr= np.arange(12)
print("Original Array" , arr)

reshaped = arr.reshape((3,4))
print ("\n Reshaped array" , reshaped)

flattened = reshaped.flatten()       # returns copy 
print("\n Flattened Array" , flattened)

raveled = reshaped.ravel()     # returnns view instead of copy
print("\n Raveled Array " , raveled)

transpose = reshaped.T
print("\n Transposed Array " , transpose)


Original Array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened Array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Raveled Array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transposed Array  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
