### Numpy Array Operations
 

In [1]:
import numpy as np

In [ ]:
arr = np.array ([1,2,3,4,5,6,7,8,9,10])

print ("Basic Slicing", arr[2:7])   # 2 ko include nhi krega but 7 ko karega
print("With Step" , arr[1:8:2])     # 2 - iska matlab every 2nd position
print("Negative Indexing" , arr[-3])    # last se 3rd value


Basic Slicing [3 4 5 6 7]
With Step [2 4 6 8]
Negative Indexing 8


In [7]:
arr_2d = np.array ([[1,2,3],   # 0th row    0,1,2 elements
                    [4,5,6],   # 1st row    0,1,2 elements
                    [7,8,9]])  # 2nd row    0,1,2 elements    
 
print("Specific Element" , arr_2d[1,2])       # 1st row ka 2nd element
print("Entire Row" , arr_2d[1])               # iska matlab puri 1st row
print("Entire Column" , arr_2d[: , 1])        # : iska matalb rows toh sari included but column bs 1 wala

Specific Element 6
Entire Row [4 5 6]
Entire Column [2 5 8]


## Sorting

In [11]:
unsorted = np.array ([3,1,4,1,5,9,2,6])
print ("Sorted Array" , np.sort (unsorted)) 

arr_2d_unsorted = np.array ( [[3,1],[1,2],[2,3]])
print ("Sorted 2D Array bu Column" , np.sort (arr_2d_unsorted , axis = 0)) 
print ("Sorted 2D Array bu Row" , np.sort (arr_2d_unsorted , axis = 1)) 

Sorted Array [1 1 2 3 4 5 6 9]
Sorted 2D Array bu Column [[1 1]
 [2 2]
 [3 3]]
Sorted 2D Array bu Row [[1 3]
 [1 2]
 [2 3]]


## Filtering

In [12]:
numbers = np.array ([1,2,3,4,5,6,7,8,9,10])
even_number = numbers [ numbers % 2 ==0]
print ("Even Numbers", even_number)


Even Numbers [ 2  4  6  8 10]


#### Filter with Mask

In [15]:
mask = numbers > 5
print ("Numbers grater than 5 :" , numbers[mask])

Numbers grater than 5 : [ 6  7  8  9 10]


### Fancy indexing vs np.where()

In [16]:
indices = [0,2,4]
print(numbers [indices] )

where_result = np.where (numbers>5)         # store krke likh diya bas same masking ki tarah
print (" NP where" , numbers [where_result])

[1 3 5]
 NP where [ 6  7  8  9 10]


In [ ]:
condition_array = np.where(numbers > 5 , numbers*4 , numbers )     # first wali main condition then baaki dono x and y hote hai 
print (condition_array) 


# np.where() -  existed code ko modify kr deta hai 


[ 1  2  3  4  5 24 28 32 36 40]


In [19]:
'''
if(numbers > 5){
    numbers*4
}
else {
    numbers
}
'''

'\nif(numbers > 5){\n    numbers*4\n}\nelse {\n    numbers\n}\n'

## Adding and Removing Data

In [23]:
arr1 = np.array ([1,2,3])
arr2 = np.array ([4,5,6])

combined = arr1 + arr2
print("It just add the rows :" ,combined)   


combined = np.concatenate ((arr1,arr2))
print("Now these two arrays are combined :" ,combined)   


It just add the rows : [5 7 9]
Now these two arrays are combined : [1 2 3 4 5 6]


## Array Compatibilty

In [25]:
a = np.array ([1,2,3])
b = np.array ([4,5,6,0])
c = np.array([7,8,9])

print ("Comaptibility Shapes : " , a.shape == b.shape)

Comaptibility Shapes :  False


### Row Addition

In [ ]:
original = np.array([[1,2],[3,4]])
new_row = np.array([5,6])

with_new_row = np.vstack((original , new_row))      # vstack se row add hoti hai 

print("Original", original)
print("New Row" , with_new_row)

Original [[1 2]
 [3 4]]
New Row [[1 2]
 [3 4]
 [5 6]]


### Column Addition

In [ ]:
original = np.array([[1,2],[3,4]])
new_column = np.array([[5],[6]])

with_new_column = np.hstack((original , new_column))        # hstack se new column add hote hai

print("Original", original)
print("New Row" , with_new_column)

Original [[1 2]
 [3 4]]
New Row [[1 2 5]
 [3 4 6]]


## Deletion 

In [35]:
arr= np.array([1,2,3,4,5])
deleted = np.delete(arr, 2)       # 2nd position ka element delete krega
print("Array after deletion" , deleted)

Array after deletion [1 2 4 5]
